version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App"
    ports:
      - "5000:5000"
  app2:
    build: ./Flask_Jinja_Tutorial/flask-jinja-tutorial
    container_name: "Flask_App2"
    ports:
      - "5001:5001"
  app3:
    build: ./Flask_WTForms_Tutorial/flask-wtforms-tutorial
    container_name: "Flask_App3"
    ports:
      - "5002:5002"
  app4:
    build: ./Routing_Flask
    container_name: "Flask_App4"
    ports:
      - "5003:5003"
  app5:
    build: ./Configure_Flask
    container_name: "Flask_App5"
    ports:
      - "5004:5004"